spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/common?currentSchema=order-service
    driver-class-name: org.postgresql.Driver






